using System;
using System.IO;
using System.Text;
using System.Collections.Generic;

class Program
{
    static void Main()
    {
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("/* ========================================= */");
        sb.AppendLine("/*      MOBILE CSS GENERATED BY C#           */");
        sb.AppendLine($"/*      DATE: {DateTime.Now:yyyy-MM-dd HH:mm}             */");
        sb.AppendLine("/*      VERSION: 4.0 (PREMIUM MOBILE WOW)    */");
        sb.AppendLine("/* ========================================= */");
        sb.AppendLine();
        
        sb.AppendLine("/* 1. THEME VARIABLES */");
        AppendThemes(sb);
        
        sb.AppendLine("/* 2. BASE RESET & TYPOGRAPHY */");
        sb.AppendLine("html, body { margin: 0; padding: 0; width: 100%; height: 100%; overflow: hidden; -webkit-tap-highlight-color: transparent; font-family: 'Inter', sans-serif; background-color: var(--bg-primary); }");
        sb.AppendLine("* { box-sizing: border-box; touch-action: manipulation; }");
        sb.AppendLine("::-webkit-scrollbar { width: 4px; height: 4px; display: none; /* Hide scrollbar on mobile for cleaner look */ }");
        
        sb.AppendLine("/* 3. PREMIUM MOBILE LAYOUT ARCHITECTURE */");
        sb.AppendLine(".dashboard-container {");
        sb.AppendLine("    display: block !important;");
        sb.AppendLine("    position: relative;");
        sb.AppendLine("    width: 100vw;");
        sb.AppendLine("    height: 100dvh;");
        sb.AppendLine("    overflow: hidden;");
        sb.AppendLine("    background-color: #000; /* Dark backdrop for scale effect */");
        sb.AppendLine("}");
        
        sb.AppendLine("/* SIDEBAR (Main View) */");
        sb.AppendLine(".sidebar {");
        sb.AppendLine("    position: absolute;");
        sb.AppendLine("    top: 0; left: 0;");
        sb.AppendLine("    width: 100%;");
        sb.AppendLine("    height: 100%;");
        sb.AppendLine("    z-index: 10;");
        sb.AppendLine("    background-color: var(--bg-card);");
        sb.AppendLine("    transition: transform 0.4s cubic-bezier(0.3, 1, 0.3, 1), filter 0.4s ease, border-radius 0.4s ease;");
        sb.AppendLine("    display: flex;");
        sb.AppendLine("    flex-direction: column;");
        sb.AppendLine("    transform-origin: center left;");
        sb.AppendLine("}");
        
        sb.AppendLine(".sidebar-header {");
        sb.AppendLine("    padding: 15px 20px !important;");
        sb.AppendLine("    border-bottom: 1px solid rgba(255,255,255,0.03) !important;");
        sb.AppendLine("}");
        
        sb.AppendLine(".chat-list {");
        sb.AppendLine("    flex: 1 !important;");
        sb.AppendLine("    overflow-y: auto !important;");
        sb.AppendLine("    padding-bottom: 150px !important;");
        sb.AppendLine("    -webkit-overflow-scrolling: touch !important;");
        sb.AppendLine("}");
        
        sb.AppendLine(".sidebar-footer {");
        sb.AppendLine("    position: absolute !important;");
        sb.AppendLine("    bottom: 0 !important;");
        sb.AppendLine("    left: 0 !important;");
        sb.AppendLine("    width: 100% !important;");
        sb.AppendLine("    padding: 15px 20px max(15px, env(safe-area-inset-bottom)) !important;");
        sb.AppendLine("    background: rgba(var(--bg-card-rgb, 2, 6, 23), 0.85) !important;");
        sb.AppendLine("    backdrop-filter: blur(16px) !important;");
        sb.AppendLine("    -webkit-backdrop-filter: blur(16px) !important;");
        sb.AppendLine("    border-top: 1px solid rgba(255,255,255,0.05) !important;");
        sb.AppendLine("    z-index: 100 !important;");
        sb.AppendLine("}");
        
        sb.AppendLine(".sidebar > div:has(> #addFriendGroupButton) {");
        sb.AppendLine("    position: absolute !important;");
        sb.AppendLine("    bottom: 80px !important;");
        sb.AppendLine("    left: 0 !important;");
        sb.AppendLine("    width: 100% !important;");
        sb.AppendLine("    z-index: 105 !important;");
        sb.AppendLine("    padding: 0 20px !important;");
        sb.AppendLine("    background: transparent !important;");
        sb.AppendLine("    display: block !important;");
        sb.AppendLine("}");
        
        sb.AppendLine(".btn-add-sidebar {");
        sb.AppendLine("    width: 100% !important;");
        sb.AppendLine("    margin: 10px 0 !important;");
        sb.AppendLine("    height: 48px !important;");
        sb.AppendLine("    border: none !important;");
        sb.AppendLine("    background: rgba(var(--accent-green-rgb, 34, 197, 94), 0.15) !important;");
        sb.AppendLine("    color: var(--accent-green) !important;");
        sb.AppendLine("    border-radius: 14px !important;");
        sb.AppendLine("    font-size: 24px !important;");
        sb.AppendLine("    transition: transform 0.2s, background 0.2s !important;");
        sb.AppendLine("}");
        sb.AppendLine(".btn-add-sidebar:active { transform: scale(0.95) !important; background: rgba(var(--accent-green-rgb, 34, 197, 94), 0.25) !important; }");
        
        sb.AppendLine(".sidebar #notificationBadge {");
        sb.AppendLine("    right: 15px !important;");
        sb.AppendLine("    top: 5px !important;");
        sb.AppendLine("}");
        
        sb.AppendLine("/* CHAT AREA (Sliding View) */");
        sb.AppendLine(".chat-area {");
        sb.AppendLine("    position: absolute;");
        sb.AppendLine("    top: 0; left: 0;");
        sb.AppendLine("    width: 100%;");
        sb.AppendLine("    height: 100%;");
        sb.AppendLine("    z-index: 20;");
        sb.AppendLine("    background-color: var(--bg-dark);");
        sb.AppendLine("    transform: translateX(100%);");
        sb.AppendLine("    transition: transform 0.4s cubic-bezier(0.3, 1, 0.3, 1), box-shadow 0.4s;");
        sb.AppendLine("    display: flex;");
        sb.AppendLine("    flex-direction: column;");
        sb.AppendLine("    box-shadow: -20px 0 50px rgba(0,0,0,0.6);");
        sb.AppendLine("}");
        
        sb.AppendLine("/* ANIMATION LOGIC - iOS style push */");
        sb.AppendLine("body.chat-open .sidebar {");
        sb.AppendLine("    transform: translateX(-25%) scale(0.96);");
        sb.AppendLine("    filter: brightness(0.4) blur(1px);");
        sb.AppendLine("    border-radius: 20px;");
        sb.AppendLine("    pointer-events: none;");
        sb.AppendLine("}");
        sb.AppendLine("body.chat-open .chat-area {");
        sb.AppendLine("    transform: translateX(0);");
        sb.AppendLine("}");
        
        sb.AppendLine("/* 4. PREMIUM COMPONENTS */");
        
        sb.AppendLine("/* Touch Targets */");
        sb.AppendLine(".mobile-back-btn, .btn-icon, .btn-send, #sendButton, .chat-input-area button {");
        sb.AppendLine("    width: 44px !important;");
        sb.AppendLine("    height: 44px !important;");
        sb.AppendLine("    display: flex;");
        sb.AppendLine("    align-items: center;");
        sb.AppendLine("    justify-content: center;");
        sb.AppendLine("    border-radius: 50% !important;");
        sb.AppendLine("    transition: transform 0.2s cubic-bezier(0.4, 0, 0.2, 1), background 0.2s !important;");
        sb.AppendLine("    background: transparent;");
        sb.AppendLine("}");
        sb.AppendLine(".mobile-back-btn:active, .btn-icon:active, .btn-send:active {");
        sb.AppendLine("    transform: scale(0.85) !important;");
        sb.AppendLine("    background: rgba(255,255,255,0.1) !important;");
        sb.AppendLine("}");
        
        sb.AppendLine("/* Chat Header - Glass */");
        sb.AppendLine(".chat-header {");
        sb.AppendLine("    padding: max(10px, env(safe-area-inset-top)) 15px 10px !important;");
        sb.AppendLine("    background: rgba(2, 6, 23, 0.75) !important;");
        sb.AppendLine("    backdrop-filter: blur(20px) !important;");
        sb.AppendLine("    -webkit-backdrop-filter: blur(20px) !important;");
        sb.AppendLine("    border-bottom: 1px solid rgba(255,255,255,0.05) !important;");
        sb.AppendLine("    z-index: 30 !important;");
        sb.AppendLine("}");
        
        sb.AppendLine("/* Messages Area */");
        sb.AppendLine(".messages-container {");
        sb.AppendLine("    flex: 1 !important;");
        sb.AppendLine("    overflow-y: auto !important;");
        sb.AppendLine("    padding: 20px 15px 90px !important;");
        sb.AppendLine("    -webkit-overflow-scrolling: touch !important;");
        sb.AppendLine("}");
        
        sb.AppendLine("/* Premium Bubbles - Kolory dziedziczone z desktopu na życzenie! */");
        sb.AppendLine(".message {");
        sb.AppendLine("    border-radius: 20px !important;");
        sb.AppendLine("    padding: 12px 16px !important;");
        sb.AppendLine("    font-size: 1.05rem !important;");
        sb.AppendLine("    line-height: 1.4 !important;");
        sb.AppendLine("    max-width: 85% !important;");
        sb.AppendLine("    box-shadow: 0 4px 15px rgba(0,0,0,0.1) !important;");
        sb.AppendLine("    margin-bottom: 12px !important;");
        sb.AppendLine("    position: relative;");
        sb.AppendLine("}");
        
        sb.AppendLine("/* Chat Input Area */");
        sb.AppendLine(".chat-input-area {");
        sb.AppendLine("    position: absolute !important;");
        sb.AppendLine("    bottom: 0 !important;");
        sb.AppendLine("    left: 0 !important;");
        sb.AppendLine("    width: 100% !important;");
        sb.AppendLine("    padding: 10px 10px max(10px, env(safe-area-inset-bottom)) !important;");
        sb.AppendLine("    background: rgba(var(--bg-card-rgb, 2, 6, 23), 0.85) !important;");
        sb.AppendLine("    backdrop-filter: blur(20px) !important;");
        sb.AppendLine("    -webkit-backdrop-filter: blur(20px) !important;");
        sb.AppendLine("    border-top: 1px solid rgba(255,255,255,0.05) !important;");
        sb.AppendLine("    border-radius: 24px 24px 0 0 !important;");
        sb.AppendLine("    box-shadow: 0 -10px 30px rgba(0,0,0,0.2) !important;");
        sb.AppendLine("    z-index: 40 !important;");
        sb.AppendLine("    display: flex !important;");
        sb.AppendLine("    align-items: center !important;");
        sb.AppendLine("    gap: 8px !important;");
        sb.AppendLine("}");
        sb.AppendLine(".chat-input-area input {");
        sb.AppendLine("    flex: 1 !important;");
        sb.AppendLine("    height: 44px !important;");
        sb.AppendLine("    border-radius: 22px !important;");
        sb.AppendLine("    background: rgba(0,0,0,0.2) !important;");
        sb.AppendLine("    border: 1px solid rgba(255,255,255,0.05) !important;");
        sb.AppendLine("    padding: 0 16px !important;");
        sb.AppendLine("    font-size: 1rem !important;");
        sb.AppendLine("    color: var(--text-main) !important;");
        sb.AppendLine("}");
        
        sb.AppendLine("/* Tiles */");
        sb.AppendLine(".friend-tile, .chat-item, .group-member-card {");
        sb.AppendLine("    height: 76px !important;");
        sb.AppendLine("    padding: 0 20px !important;");
        sb.AppendLine("    border-radius: 16px !important;");
        sb.AppendLine("    margin: 4px 10px !important;");
        sb.AppendLine("    background: transparent !important;");
        sb.AppendLine("    transition: background 0.2s, transform 0.2s !important;");
        sb.AppendLine("}");
        sb.AppendLine(".friend-tile:active, .chat-item:active, .group-member-card:active {");
        sb.AppendLine("    background: rgba(255,255,255,0.05) !important;");
        sb.AppendLine("    transform: scale(0.98) !important;");
        sb.AppendLine("}");
        sb.AppendLine(".friend-tile .avatar, .chat-item .avatar, .group-member-card .avatar {");
        sb.AppendLine("    width: 50px !important;");
        sb.AppendLine("    height: 50px !important;");
        sb.AppendLine("}");
        
        sb.AppendLine("/* Tablets & Larger Mobile (Landscape) */");
        sb.AppendLine("@media (min-width: 600px) {");
        sb.AppendLine("    .message { max-width: 70% !important; }");
        sb.AppendLine("    .dashboard-container { display: flex !important; }");
        sb.AppendLine("}");
        
        sb.AppendLine("/* Conversation Sidebar (Info / Admin) */");
        sb.AppendLine(".conversation-sidebar {");
        sb.AppendLine("    position: fixed;");
        sb.AppendLine("    top: 0; right: -100%;");
        sb.AppendLine("    width: 100% !important;");
        sb.AppendLine("    height: 100dvh !important;");
        sb.AppendLine("    z-index: 2000 !important;");
        sb.AppendLine("    background-color: var(--bg-card);");
        sb.AppendLine("    transition: right 0.3s cubic-bezier(0.4, 0, 0.2, 1);");
        sb.AppendLine("    display: flex;");
        sb.AppendLine("    flex-direction: column;");
        sb.AppendLine("}");
        sb.AppendLine(".conversation-sidebar.open { right: 0 !important; }");
        sb.AppendLine(".conversation-sidebar-header { padding: 15px; border-bottom: 1px solid var(--border-color); display: flex; align-items: center; justify-content: space-between; }");
        sb.AppendLine(".conversation-sidebar-body { flex: 1; overflow-y: auto; padding: 15px; }");
        sb.AppendLine(".admin-controls { display: flex; flex-direction: column; gap: 10px; margin-top: 20px; }");
        sb.AppendLine(".btn-sidebar-action { width: 100%; padding: 12px; text-align: left; display: flex; align-items: center; gap: 10px; background: rgba(255,255,255,0.05); border: none; border-radius: 8px; color: var(--text-main); }");
        sb.AppendLine(".btn-sidebar-action:active { background: rgba(255,255,255,0.1); }");
        
        sb.AppendLine("/* DELETE CONFIRM OVERLAY */");
        sb.AppendLine(".custom-confirm-overlay { position: fixed; top: 0; left: 0; width: 100%; height: 100%; background-color: rgba(0, 0, 0, 0.85); display: none; align-items: center; justify-content: center; z-index: 3000; backdrop-filter: blur(8px); opacity: 0; transition: opacity 0.3s ease; }");
        sb.AppendLine(".custom-confirm-overlay.show { display: flex !important; opacity: 1; }");
        sb.AppendLine(".custom-confirm-box { background: var(--bg-card); border: 1px solid var(--border-color); border-radius: 20px; padding: 25px; width: 90%; max-width: 350px; text-align: center; box-shadow: 0 20px 50px rgba(0,0,0,0.5); transform: scale(0.9); transition: transform 0.3s cubic-bezier(0.34, 1.56, 0.64, 1); }");
        sb.AppendLine(".custom-confirm-overlay.show .custom-confirm-box { transform: scale(1); }");
        
        sb.AppendLine("/* Modals */");
        sb.AppendLine(".modal-content {");
        sb.AppendLine("    width: 100% !important;");
        sb.AppendLine("    height: 100dvh !important;");
        sb.AppendLine("    max-height: 100dvh !important;");
        sb.AppendLine("    border-radius: 0 !important;");
        sb.AppendLine("    margin: 0 !important;");
        sb.AppendLine("    display: flex !important;");
        sb.AppendLine("    flex-direction: column !important;");
        sb.AppendLine("    overflow: hidden !important;");
        sb.AppendLine("    animation: slideUpModal 0.4s cubic-bezier(0.2, 0.8, 0.2, 1) forwards !important;");
        sb.AppendLine("}");
        sb.AppendLine("@keyframes slideUpModal { from { transform: translateY(100%); } to { transform: translateY(0); } }");
        sb.AppendLine(".modal-body {");
        sb.AppendLine("    flex: 1 !important;");
        sb.AppendLine("    overflow-y: auto !important;");
        sb.AppendLine("    -webkit-overflow-scrolling: touch !important;");
        sb.AppendLine("    padding: 15px !important;");
        sb.AppendLine("}");
        
        sb.AppendLine("/* Settings sidebar tabs in a 2x2 grid */");
        sb.AppendLine(".modal-tabs {");
        sb.AppendLine("    display: grid !important;");
        sb.AppendLine("    grid-template-columns: 1fr 1fr !important;");
        sb.AppendLine("    gap: 10px !important;");
        sb.AppendLine("    padding: 10px 15px !important;");
        sb.AppendLine("    margin-bottom: 15px !important;");
        sb.AppendLine("}");
        sb.AppendLine(".tab-button {");
        sb.AppendLine("    width: 100% !important;");
        sb.AppendLine("    padding: 10px 10px !important;");
        sb.AppendLine("    border-radius: 20px !important;");
        sb.AppendLine("    background: rgba(255,255,255,0.05) !important;");
        sb.AppendLine("    border: none !important;");
        sb.AppendLine("    white-space: nowrap !important;");
        sb.AppendLine("    text-align: center !important;");
        sb.AppendLine("    font-size: 0.9rem !important;");
        sb.AppendLine("}");
        sb.AppendLine(".tab-button.active {");
        sb.AppendLine("    background: var(--accent-green) !important;");
        sb.AppendLine("    color: #fff !important;");
        sb.AppendLine("}");
        
        sb.AppendLine("/* UTILITIES GENERATOR */");
        GenerateUtilities(sb);

        string outputPath = @"c:/Users/user/Music/Komunikator JGS/V 13/Client/mobile.css";
        File.WriteAllText(outputPath, sb.ToString());
        Console.WriteLine($"[WOW EDITION] Generated premium mobile.css with {sb.ToString().Split('\n').Length} lines to {outputPath}");
    }

    static void AppendThemes(StringBuilder sb)
    {
        sb.AppendLine(":root[data-theme=\"original\"] { --bg-dark: #020617; --bg-card: #020617; --input-bg: #020617; --text-main: #e5f9f0; --text-muted: #9ca3af; --text-secondary: #6b7280; --accent-green: #22c55e; --accent-green-hover: #4ade80; --border-color: #0f172a; --border-green: rgba(34, 197, 94, 0.55); --error-color: #f97373; --bg-primary: #020617; --settings-tabs-bg: #020617; --settings-sub-bg: #020617; --bg-card-rgb: 2, 6, 23; --accent-green-rgb: 34, 197, 94; }");
        sb.AppendLine(":root[data-theme=\"neon\"] { --bg-dark: #050816; --bg-card: #050816; --input-bg: #050816; --text-main: #e5e7eb; --text-muted: #9ca3af; --text-secondary: #a5b4fc; --accent-green: #f97316; --accent-green-hover: #fb7185; --border-color: #111827; --border-green: rgba(249, 115, 22, 0.6); --error-color: #fb7185; --bg-primary: #020617; --settings-tabs-bg: #020617; --settings-sub-bg: #020617; --bg-card-rgb: 5, 8, 22; --accent-green-rgb: 249, 115, 22; }");
        sb.AppendLine(":root[data-theme=\"forest\"] { --bg-dark: #022c22; --bg-card: #022c22; --input-bg: #064e3b; --text-main: #ecfdf5; --text-muted: #a7f3d0; --text-secondary: #6ee7b7; --accent-green: #16a34a; --accent-green-hover: #22c55e; --border-color: #064e3b; --border-green: rgba(34, 197, 94, 0.6); --error-color: #f97373; --bg-primary: #022c22; --settings-tabs-bg: #022c22; --settings-sub-bg: #064e3b; --bg-card-rgb: 2, 44, 34; --accent-green-rgb: 22, 163, 74; }");
        sb.AppendLine(":root[data-theme=\"kontrast\"] { --bg-dark: #000000; --bg-card: #000000; --input-bg: #000000; --text-main: #ffffff; --text-muted: #ffff00; --text-secondary: #00ffff; --accent-green: #ffff00; --accent-green-hover: #ffffff; --border-color: #ffffff; --border-green: #ffff00; --error-color: #ff0000; --bg-primary: #000000; --settings-tabs-bg: #000000; --settings-sub-bg: #000000; --btn-text-color: #000000; --bg-card-rgb: 0, 0, 0; --accent-green-rgb: 255, 255, 0; }");
    }

    static void GenerateUtilities(StringBuilder sb)
    {
        for (int i = 0; i <= 50; i += 5)
        {
            sb.AppendLine($".m-{i} {{ margin: {i}px !important; }}");
            sb.AppendLine($".p-{i} {{ padding: {i}px !important; }}");
        }
        for (int i = 0; i <= 100; i += 10)
        {
            sb.AppendLine($".w-{i}p {{ width: {i}% !important; }}");
        }
        sb.AppendLine(".glass-panel { background: rgba(255,255,255,0.05); backdrop-filter: blur(10px); -webkit-backdrop-filter: blur(10px); border: 1px solid rgba(255,255,255,0.05); border-radius: 16px; }");
        
        // Add some useful utility classes that were in previous versions
        for (int i = 8; i <= 40; i++)
        {
            sb.AppendLine($".fs-{i} {{ font-size: {i}px !important; }}");
        }
        string[] flexProps = { "center", "flex-start", "flex-end", "space-between", "space-around" };
        foreach (var p in flexProps)
        {
            sb.AppendLine($".justify-{p} {{ justify-content: {p} !important; }}");
            sb.AppendLine($".align-{p} {{ align-items: {p} !important; }}");
        }
    }
}
